### ISSUE TITLE
ath79-generic target

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/site-ffm#103]
Since both the OpenWrt upstream and the Gluon upstream migrate the ar71xx target to ath79, we should also consider this here.
https://github.com/freifunk-gluon/gluon/blob/master/targets/ath79-generic

https://openwrt.org/releases/21.02/notes-21.02.0-rc2#dropped_hardware_targets
https://openwrt.org/docs/techref/targets/ar71xx-ath79

**Comment by awlx** [comment]
That's already done in the next branch ;).

https://github.com/freifunkMUC/site-ffm/blob/next/Makefile#L9
