### ISSUE TITLE
Use the Projects section of this repository for our "ToDos"

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/site-ffm#104]
I would suggest using the Projects tab to list the current ToDos and Issues and see which ones are being worked on by whom.

**Comment by awlx** [comment]
While it's a good idea I think we should open a project at the organisation level. So we can move work items from all repos around.

**Comment by goligo** [comment]
I have created the project "Firmware" in freifunkMUC. I could not add community-packages as tracked repository, as it does not have "issues" enabled.
