### ISSUE TITLE
Use mergeable to check whether a new changelog entry has been created

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/site-ffm#170]
We might want to keep a record of the changes we have made in our changelog file. Since one might forget to do this when creating a PR, we should use Mergeable to remind them to add the changes to the changelog (https://mergeable.readthedocs.io/en/latest/configuration.html)

**Comment by awlx** [comment]
We should get rid of the manual changelog file and use autogenerated release changelogs.

**Comment by awlx** [comment]
Like this:
https://github.com/freifunkMUC/site-ffm/releases/tag/v2022.2.1
