### ISSUE TITLE
GitHub Action for releases fails randomly

### ISSUE THREAD

**Issue by grische** [freifunkMUC/site-ffm#236]
While the action itself seem to work fine, the upload of items seem to fail. Needs further investigation:
https://github.com/freifunkMUC/site-ffm/actions/runs/4335649576/attempts/2

**Comment by grische** [comment]
Upstream bug report https://github.com/softprops/action-gh-release/issues/353

**Comment by GoliathLabs** [comment]
We could settle for this action instead https://github.com/ncipollo/release-action. It doesn't appear to have the same problem

**Comment by grische** [comment]
One of the updates seem to have fixed this
