### ISSUE TITLE
Integration des site-select packages

### ISSUE THREAD

**Issue by chris007de** [freifunkMUC/site-ffm#24]
Habe mal das gluon-config-mode-site-select Paket (https://github.com/freifunk-gcp/v2015.1) in unseren aktuellen Master gebaut.

Damit kann man mehrere site.confs in eine Firmware integrieren und sie im Gluon Luci und per Kommandozeile umschalten.
![](https://camo.githubusercontent.com/5f2512fd1b107827783b8dd69aa5046f00018cf6/687474703a2f2f6c61626f7231392e6e65742f48656e6472696b2f70726576696577312e706e67)

Bis auf die bekannte Bindestrich-Allergie von lua gab es keine Probleme, allerdings musste ich den site-code von ffmuc-umland in ffmuc_umland aendern damit es reibungslos funktioniert.
Ausserdem gibt es Probleme beim kompilieren, wenn unsere custom gluon-ebtables-filter-... Pakete eingebaut werden sollen.
Es gibt allerdings noch einiges zu testen und fixen bevor man daran denken koennte das zu verwenden:

- [x] Upgrade von aktueller gluon-ffmuc-v2015.5 Firmware auf Firmware mit site-select (site.conf muss nach Upgrade identisch mit ffmuc.conf sein)

> :+1: Funktioniert. Die alte site.conf wird mit neuer site.conf mit entsprechendem site-code ersetzt (ffmuc -> ffmuc).

- [x] Upgrade von aktueller gluon-ffmuc-umland-v2015.6 Firmware auf Firmware mit site-select (site.conf muss nach Upgrade trotz Aenderung von des site-codes von "ffmuc-umland" auf "ffmuc_umland" identisch mit ffmuc_umland.conf sein)
 
> :-1: Funktioniert nicht. Landet bei ffmuc.

- [x] Was passiert bei einem Upgrade auf eine Firmware, bei der der aktuell ausgewaehlte site-code nicht mehr verfuegbar ist?

> Ist der alte site-code nicht mehr in der neuen Firmware, wird auf den default site-code zurueckgefallen. -> Das hilft beim zweiten Testcase! Um von ffmuc-umland auf ffmuc_umland zu kommen, muss dort einfach eine Firmware mit ffmuc_umland als default site.conf verteilt werden.

- [ ] Herausfinden, warum unsere gluon-ebtables-filter Pakete nicht mit eingebaut werden koennen und fixen

:beers: 

**Hinweis**: "Default site.conf" ist die site.conf, die nicht nur als *./site-ffm/extras/\<site-code>.conf* existiert, sondern auch nochmal explizit als *./site-ffm/site.conf*.

**Comment by chris007de** [comment]
Einige Testergebnisse:
* Basis: gluon-ffmuc-v2015.5 (ffmuc) <br>
  Sysupgrade: gluon-ffmuc-v2015.5-site-select (default=ffmuc, ffmuc_umland) <br>
  => ffmuc :+1: 
* Basis: gluon-ffmuc-umland-v2015.6 (ffmuc-umland) <br>
  Sysupgrade: gluon-ffmuc-v2015.5-site-select (default=ffmuc, ffmuc_umland) <br>
  => ffmuc :-1: 
* Basis: gluon-ffmuc-umland-v2015.6 (ffmuc-umland) <br>
  Sysupgrade: gluon-ffmuc-v2015.5-site-select (ffmuc, default=ffmuc_umland) <br>
  => ffmuc_umland :+1: 
* Basis: gluon-ffmuc-v2015.5-site-select (eingestellt auf ffmuc) <br>
  Sysupgrade: gluon-ffmuc-v2015.5-site-select (ffmuc, default=ffmuc_umland) <br>
  => ffmuc :+1: 
* Hin- und herwechseln zwischen ffmuc und ffmuc_umland mittels Luci config mode und uci ueber SSH: :+1:

**Comment by fpletz** [comment]
Ist drin und funktioniert: https://github.com/freifunkMUC/site-ffm/commit/7f3333a684e48109130455a1be878fb8df468279
