### ISSUE TITLE
Add Segment Wertingen

### ISSUE THREAD

**Issue by istrator2** [freifunkMUC/site-ffm#243]
In the next segment expansion _Wertingen_ please also create.

Hoping it will help with fundraising ;)

**Comment by awlx** [comment]
Which SSID would you prefer? werting.freifunk.net (you probably also want the domain then) or something else?

**Comment by istrator2** [comment]
I would appreciate **wertingen.freifunk.net** very much.

You are right. We would also like to have the domain - but we don't have much plans there. Just a _powered by Freie Netze München e.V._ and a redirect to ffmuc.net.

Who do I have to talk to, or does that fall right into the project with the TLS certificates?

**Comment by awlx** [comment]
I think you somehow have to ask freifunk.net for the domain and then @DasSkelett and @GoliathLabs can add it. Maybe they can assist here :).

**Comment by ce-4** [comment]
Seconding wertingen as segment name (werting would raise eyebrows), or maybe DLG for the whole Landkreis :)

**Comment by istrator2** [comment]
I already found where to apply for the domain.
https://freifunk.net/kontakt/issuetracker/
What do I want?


A-record to an existing IP address
or
DNS record to two existing DNS servers for the subdomain

**Comment by istrator2** [comment]
> DNS-Record auf  anycast01.ffmuc.net

requested via issuetracker.

**Comment by istrator2** [comment]
Freifunk.net schreibt

> Hallo istrator²,
> (...)
> wertingen.freifunk.net.	7200	IN	CNAME	anycast.ffmuc.net.
> 
> ist aktiv.
> 
> have fun! 😄

**Comment by istrator2** [comment]
Bitte 2x /22 Netzsegmente anlegen.

Für die SSID in Spe wertingen.freifunk.net 
Eins für Normalbetrieb und eins für Events/Großinstallationen.

Siehe Chat @NOC 28.09.23 10:15

**Comment by grische** [comment]
@awlx @GoliathLabs @DasSkelett do we already have a prefix that can be added to the firmware?

**Comment by grische** [comment]
Following our previous IP numbering scheme for adding new domains, I added two new domains for wertingen in #266

Can someone review and implement this on the gateways?

**Comment by grische** [comment]
Merged in #318 and will be part of the next release
