### ISSUE TITLE
simplify cut-and-paste of meshviewer coordinates into configmode

### ISSUE THREAD

**Issue by mrmadcow** [freifunkMUC/site-ffm#25]
1) provide coordinates in meshviewer (on right click) in '$LAT; $LON' format
2) allow pasting coordinates in the above format into luci, alternatively to using two fields. If first field contains semicolon and second field is empty the string will be split. This should be documented on the wizard page

**Comment by chris007de** [comment]
wrong repo, moved this issue to https://github.com/freifunkMUC/meshviewer/issues/13
