### ISSUE TITLE
Include ebtables-source-filter

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/site-ffm#46]
To not route private networks to the broad network.

Doc: https://gluon.readthedocs.io/en/v2018.1.x/package/gluon-ebtables-source-filter.html

**Comment by krombel** [comment]
Implemented in 894453a809f562ac

**Comment by krombel** [comment]
Reopen as IPv6 is not working

**Comment by rotanid** [comment]
https://gluon.readthedocs.io/en/v2018.2.x/package/gluon-ebtables-source-filter.html
you need an additional config

**Comment by rotanid** [comment]
i'm not entirely sure about it, but maybe you could specify your whole subnet as extra_prefixes6 in every domain. maybe @mweinelt can say whether this is an acceptable easier way than specifying each /64 sperately

**Comment by krombel** [comment]
The question is: What would be the benefit of each config:
- Joined
  - People might roam between zones - isn't that filtered gateway-side? - so this is no point in that case
- Separately
  - You have a strict separation
  - As nodes will not forward it upstream => no rubbish from nodes roaming as they won't get a response either way

Is that right so far @rotanid?

**Comment by rotanid** [comment]
you're probably right, but as i didn't use domains myself so far, i can't provide the perfect answer/solution

**Comment by krombel** [comment]
We added extra_prefixes6 and now it seems to be working.
We will go for setup dedicated IPv6-Adresses for each domain for now.

The IPv6-Issue got fixed in 13dec0e17574860b37e895065ba266e10373d4c6
