### ISSUE TITLE
Implement usage of vxlan

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/site-ffm#48]
instead of broadcasts for mesh-on-lan

**Comment by krombel** [comment]
preparations done. Enabling will be shifted to v2019.1 for now

**Comment by krombel** [comment]
currently on hold because of #54 and #56 . Although those is related to BATMAN_V and not vxlan it is quite likely that they will fix the current issues we have with vxlan.

=> It is working as expected on the new segments but there are monitoring issues

**Comment by awlx** [comment]
Can't we close this?
