### ISSUE TITLE
./002-domain-migration:3: module 'nixio.fs' not found:

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/site-ffm#53]
Device: WR841ND v10
Migration from v2019.0-beta1 => v2019-exp~13

Further data:
https://chat.ffmuc.net/freifunk/pl/7p795dzwmpnbpdz4x3rub77ezy

**Comment by rotanid** [comment]
nixio is not part of Gluon v2018.2, see the release notes under "Internals"
https://gluon.readthedocs.io/en/v2018.2.x/releases/v2018.2.html

**Comment by krombel** [comment]
fixed by https://github.com/freifunkMUC/gluon-packages/pull/6
