### ISSUE TITLE
user forward on offloader shows lower traffic

### ISSUE THREAD

**Issue by krombel** [freifunkMUC/site-ffm#58]
While node shows correct transfer rate the offloader shows a much lower traffic as can be seen in the following images:
![traffic-node](https://user-images.githubusercontent.com/11167142/58252978-a41d5500-7d67-11e9-8c9e-75b105b00da8.png)
![traffic-offloader](https://user-images.githubusercontent.com/11167142/58252984-a7b0dc00-7d67-11e9-9d04-40eab5fa7b81.png)

**Comment by awlx** [comment]
Is this still an issue or was this already fixed with release of Wireguard?
